package com.psychiatrygarden.http;

import com.psychiatrygarden.ProjectApp;
import com.ykb.ebook.common.UrlConfigKt;

/* loaded from: classes4.dex */
public class NetworkRequestsURL {
    public static final String CHANNEL_LIST;
    public static final String COMMENT_TEMP_POINT;
    public static final String EXAM_BASE_URL;
    public static final String EXAM_RANKING;
    public static final String GET_EXAM_INFO;
    public static final String GET_QUESTION;
    public static final String GET_USER_ANSWER_RECORD;
    public static final String QUESTION_AD_CONFIG;
    public static final String QUESTION_EXPOSE;
    public static final String SUBMIT_ANSWER_RECORD;
    public static final String SUBMIT_CHANNEL;
    public static final String USER_EXAM;
    public static final String WxLogin;
    public static final String accessLogUrl;
    public static String addArticle = null;
    public static String addBlackListApi = null;
    public static String addBook = null;
    public static String addManagerApi = null;
    public static String addNoteApi = null;
    public static String addOrCancel = null;
    public static String addUserCategorySort = null;
    public static final String addUserQuestionIdentity;
    public static String adminUpdateLabelCountApi = null;
    public static String adsInCommentApi = null;
    public static String aliyunCredentials = null;
    public static final String analysisPraise;
    public static final String anonymousPushCircleConfig;
    public static String appTestFeedBack = null;
    public static String appTestInfo = null;
    public static final String appTestVersionInfo;
    public static String articleList = null;
    public static String authCodeEmail = null;
    public static String bannedSingleMemberApi = null;
    public static final String bindMobileLogin;
    public static final String bindUserSchool;
    public static final String bindWx;
    public static final String blackList;
    public static String bookList = null;
    public static String bookStackList = null;
    public static final String buyFilePermission;
    public static String buyInfoV2Api = null;
    public static final String cancelFollowSchool;
    public static String cancellationApi = null;
    public static String changeEmail = null;
    public static final String changeMobile;
    public static final String changeUserInfo;
    public static String chapterApi = null;
    public static String chapterLockApi = null;
    public static String chatAnnouncementApi = null;
    public static String chatCategoryApi = null;
    public static String chatDetailApi = null;
    public static String chatJoinApi = null;
    public static String chatListApi = null;
    public static String chatMemberApi = null;
    public static String chatRecordingTimeApi = null;
    public static String chatSignOutApi = null;
    public static final String checkChangeNickname;
    public static final String checkCouponUrl;
    public static final String checkSocialLoginBind;
    public static final String chooseChapter;
    public static final String chooseSchool1V1;
    public static final String chooseSchoolCalendar;
    public static final String chooseSchoolChooseInfo;
    public static final String chooseSchoolFeedBackCS;
    public static final String chooseSchoolFilterData;
    public static final String chooseSchoolGetPermissionFree;
    public static final String chooseSchoolGetPermissionGetFreePop;
    public static final String chooseSchoolGetPermissionList;
    public static final String chooseSchoolKingKongArea;
    public static final String chooseSchoolMajorList;
    public static final String chooseSchoolNoticeList;
    public static final String chooseSchoolPermissionBtn;
    public static final String chooseSchoolQuestionDetail;
    public static final String chooseSchoolQuestionList;
    public static final String chooseSchoolSaveScore;
    public static final String chooseSchoolSchoolList;
    public static final String chooseSchoolTargetSchool;
    public static final String chooseSchoolTargetSchoolOpera;
    public static final String chooseSchoolTopSchoolInfo;
    public static String circleReport = null;
    public static final String cleanNoteURL;
    public static final String cleanUnredNumberMsg;
    public static final String cleancollectionApi;
    public static String clearAllAnswerApi = null;
    public static String clearAllAnswerNoticeApi = null;
    public static String clearAnswerApi = null;
    public static final String clearNoteApi;
    public static String collectApi = null;
    public static String collectVideoApi = null;
    public static final String columnSortURL;
    public static final String combinePaperColumn;
    public static final String combineQuestion;
    public static final String combineQuestionFilterOptions;
    public static final String combineRedo;
    public static String commentRuleApi = null;
    public static String commenthotApi = null;
    public static String commsearchApi = null;
    public static String communityCategoryApi = null;
    public static String communitySeeApi = null;
    public static String confirmVerifyCode = null;
    public static String couponsList = null;
    public static String courseBannerLiving = null;
    public static String courseCategoryTab = null;
    public static final String courseCommentList;
    public static String courseCourseSpecial = null;
    public static final String courseDetail;
    public static String courseDetailInfo = null;
    public static String courseDirectoryCollect = null;
    public static String courseDirectoryCombine = null;
    public static String courseDirectoryNote = null;
    public static String courseDirectoryTab = null;
    public static final String courseGiftList;
    public static String courseJIANG_YI = null;
    public static String courseLearnCenterDay = null;
    public static String courseLearnCenterList = null;
    public static String courseMainList = null;
    public static String courseMainListSearch = null;
    public static String courseNoteExport = null;
    public static String courseQRCode = null;
    public static String courseSpecialList = null;
    public static final String courseStructure;
    public static final String courseSurveyList;
    public static final String courseUnlock;
    public static final String courseVideoAddNote;
    public static final String courseVideoCollect;
    public static final String courseVideoNoteList;
    public static String courselistApi = null;
    public static String coursevideoApi = null;
    public static String curriculumCategroyUrl = null;
    public static String curriculumListUrl = null;
    public static String curriculumcollectUrl = null;
    public static String curriculumdetailUrl = null;
    public static String curriculummyCollectionUrl = null;
    public static String curriculummyCommentUrl = null;
    public static String curriculummyNoteUrl = null;
    public static String curriculumseeUrl = null;
    public static String curriculumstateUrl = null;
    public static String curriculumtryAndSeeUrl = null;
    public static final String cutQuestion;
    public static String dailyDataByDate = null;
    public static String dailyTaskData = null;
    public static String dailyTaskReset = null;
    public static String dailyUpdateTime = null;
    public static String delBook = null;
    public static final String delCollection;
    public static String delHistoryRecord = null;
    public static String deleTieziUrl = null;
    public static final String deleteCombineQuestion;
    public static final String deleteUserAddress;
    public static final String deleteVideoNote;
    public static final String departmentMajor;
    public static final String departmentMajorDirection;
    public static final String departmentSchool;
    public static final String doQuestionBuryPoint;
    public static String downloadFileCount = null;
    public static final String downloadVideoBuryPoint;
    public static String editArticle = null;
    public static String editArticleNew = null;
    public static String editReceivingAddressApi = null;
    public static String editorLikesApi = null;
    public static final String enableExpModule;
    public static final String errorCorrectionGettypeURL;
    public static final String errorCorrectionListURL;
    public static final String errorCorrectionNewListURL;
    public static final String errorCorrectionPraiseURL;
    public static final String errorCorrectionReplyListURL;
    public static final String errorCorrectionSaveURL;
    public static String estimatedChange = null;
    public static String exchangecodeApi = null;
    public static String exchangelistApi = null;
    public static String follerListApi = null;
    public static final String followMajor;
    public static final String followSchool;
    public static final String followSchoolList;
    public static String forumSearchCategoryData = null;
    public static String forumSearchCategoryFilterData = null;
    public static String forumTopData = null;
    public static String generateHelpCode = null;
    public static String getAccumulateActiveRankList = null;
    public static final String getAdjustInfo;
    public static String getAdjustQrCodeInfo = null;
    public static String getAdjustRankList = null;
    public static final String getAdmissionBrochure;
    public static String getAllRankInfo = null;
    public static String getAnnouncementApi = null;
    public static String getAppProject = null;
    public static String getArticleInfo = null;
    public static String getArticleList = null;
    public static final String getCircleAccess;
    public static final String getClassNotice;
    public static final String getCommentCountaid = "";
    public static String getCommentRankList = null;
    public static final String getComputerRuleInfo;
    public static final String getComputerStatisticsInfo;
    public static String getContinuousActiveRankList = null;
    public static final String getCorrectionRulesURL;
    public static final String getCoupon;
    public static String getCourseAkApi = null;
    public static String getCourseDataurl = null;
    public static String getCourseNewApi = null;
    public static final String getDepartmentList;
    public static final String getDepartmentMajorInfoList;
    public static final String getDepartmentSchoolEnrollment;
    public static String getDoQuetionRankList = null;
    public static String getEntranceTimeApi = null;
    public static String getForumBottomStatus = null;
    public static String getForumHotRank = null;
    public static final String getFreeCourse;
    public static String getGroupCodeApi = null;
    public static String getH5ShareUrl = null;
    public static String getIdentityChapter = null;
    public static String getIdentityLabel = null;
    public static String getInformationList = null;
    public static String getInputInviteCodeURL = null;
    public static String getInviteListUrl = null;
    public static String getInvitePageURL = null;
    public static String getJobList = null;
    public static final String getKnowledgeOutlinesQuestion;
    public static final String getKnowledgeQuestion;
    public static String getKnowledgeTask = null;
    public static final String getMajorEnrollment;
    public static final String getMajorRecruitInfo;
    public static final String getMajorScoreInfo;
    public static final String getMessageNotice;
    public static final String getMockModeStatisticsInfo;
    public static final String getMockPopData;
    public static final String getMockStatisticsChatData;
    public static String getNoteApi = null;
    public static final String getNoteURL;
    public static String getNoteurl = null;
    public static String getNoticeApi = null;
    public static final String getOpenMajorList;
    public static String getParentCate = null;
    public static String getPostRankList = null;
    public static final String getPraiseNoticeList;
    public static String getPraiseRankList = null;
    public static String getPrivacyApi = null;
    public static final String getProvinceOrSchool;
    public static String getQuestionAndUnitSheet = null;
    public static final String getRecruitInfo;
    public static final String getRecruitInfoSearchParams;
    public static final String getReplyCommentCount;
    public static String getRewardList = null;
    public static final String getSchoolEnrollment;
    public static final String getSchoolListForMajor;
    public static final String getSchoolMajor;
    public static final String getSchoolMajorDirection;
    public static final String getScoreLine;
    public static final String getScoreLineParams;
    public static final String getShareTask;
    public static String getShengYunGoodsNet = null;
    public static String getShengYunSet = null;
    public static String getSignLog = null;
    public static String getSignRanking = null;
    public static String getSortListUrl = null;
    public static String getSourceInfoById = null;
    public static String getStatisticalPercentInfo = null;
    public static String getStatisticalRankData = null;
    public static String getStatisticalTab = null;
    public static String getStatisticalTopData = null;
    public static String getTodayStatisticalData = null;
    public static String getUserEducationApi = null;
    public static String getUserInfoApi = null;
    public static String getUserTypeApi = null;
    public static String getVideos = null;
    public static String getWordInfoApi = null;
    public static String getactiveApi = null;
    public static String getallAnalysisApi = null;
    public static String getanswerApi = null;
    public static String getchapterApi = null;
    public static String getcollectionApi = null;
    public static String getforumDCollectionInfoApi = null;
    public static String getforumDDeteleInfoApi = null;
    public static String getforumDetailInfoApi = null;
    public static String getforumDpraiseInfoApi = null;
    public static String getforumTopApi = null;
    public static String getforumauthenticationApi = null;
    public static String getforumchildrenApi = null;
    public static String getforumdetailApi = null;
    public static String getforumeditIntroductionApi = null;
    public static String getforumeditPraiseApi = null;
    public static String getforumeexitApi = null;
    public static String getforumfollowApi = null;
    public static String getforumgroupApi = null;
    public static String getforumindexApi = null;
    public static String getforumlabellistApi = null;
    public static String getforumlistApi = null;
    public static String getforummemberApi = null;
    public static String getforumpostingApi = null;
    public static String getforumrecordingTimeApi = null;
    public static String getforumsearchDataApi = null;
    public static String getforumuploadImageApi = null;
    public static String getforumviewApi = null;
    public static String getforumvoteApi = null;
    public static String getgiveLogApi = null;
    public static String getmyAnalysisApi = null;
    public static String getnoteApi = null;
    public static String getpostNoteApi = null;
    public static String getsaveAnalysisApi = null;
    public static String getstatApi = null;
    public static final String gfRanking;
    public static final String goodsCategory;
    public static final String goodsCategoryUrl;
    public static final String goodsDetailHtmlUrl;
    public static final String goodsDetailNewURL;
    public static final String goodsDetailURL;
    public static final String goodsList;
    public static final String goodsListUrl;
    public static final String goodsSearch;
    public static String gradeApi = null;
    public static String gradeApi2 = null;
    public static String gradeformApi = null;
    public static String gradeformRankApi = null;
    public static String handleWatchedApi = null;
    public static String handout_comment_search = null;
    public static String homePageSmallAdApi = null;
    public static String hotCircle = null;
    public static final String hotMajorList;
    public static final String hotSchoolList;
    public static final String incrViewCount;
    public static final String indexForMajorList;
    public static final String indexForSchoolList;
    public static String infoApi = null;
    public static String infoCollection = null;
    public static String infoUrl = null;
    public static String infomationShareCount = null;
    public static String interAction = null;
    public static String isscategoryUrl = null;
    public static String issdetailUrl = null;
    public static final String joinAppTest;
    public static String kefucsApi = null;
    public static String knowledgeList = null;
    public static String knowledgeList_zz_zt = null;
    public static final String knowledgeNodeList;
    public static final String knowledgeQuestionList;
    public static String knowledgeTaskList = null;
    public static String knowlwdgeMapOne = null;
    public static String knowlwdgeMapPoint = null;
    public static String knowlwdgePointDetail = null;
    public static String knowlwdgePointTopData = null;
    public static String listWithRuleApi = null;
    public static String liveCalendarLiveDataList = null;
    public static String liveCalendarLiveDate = null;
    public static final String liveHandout;
    public static final String mAdUrl;
    public static final String mAddCollectionUrl;
    public static final String mAddCommentShareUrl;
    public static final String mAddOrderURL = "";
    public static final String mAddShareUrl;
    public static final String mAddUsortUrl;
    public static final String mAnsweredQuestionURL;
    public static final String mAvatar2URL;
    public static String mBanUrl = null;
    public static String mCategoryListNewUrl = null;
    public static final String mChatFollow;
    public static final String mChatFollowlist;
    public static final String mChatGetToken;
    public static final String mChatUnFollow;
    public static final String mCheckVersionUrl;
    public static final String mClearAnsweredURL;
    public static final String mClearCollectionURL;
    public static final String mClearNoteURL;
    public static String mCollectSetUrl = null;
    public static final String mCollectionURL;
    public static String mCommentIameUrl3 = null;
    public static String mCommentList = null;
    public static String mCommentShareInfo = null;
    public static String mCommlogUrl = null;
    public static final String mCourseAddNoteURL;
    public static final String mCourseClearNoteURL;
    public static final String mCourseNoteListURL;
    public static final String mCoursePlayNum;
    public static final String mCourseVideoDaka;
    public static final String mCoursedelete = "";
    public static final String mCreatePayOrderURL = "";
    public static String mCustomTopicListApi = null;
    public static String mDeleteUrl = null;
    public static String mDepartmentUrl = null;
    public static String mDigest = null;
    public static String mEsexUrl = null;
    public static String mExamListSetMoreUrl = null;
    public static String mExamListSetUrl = null;
    public static final String mFeedUrl;
    public static String mGetCommentReplyUrl = null;
    public static final String mGetCourse;
    public static final String mGetGnjsHtmlUrl = "https://m.yikaobang.com.cn/app/introduce.html";
    public static final String mGetGoodslistURL = "";
    public static final String mGetGyHtmlUrl = "https://m.yikaobang.com.cn/app/aboutus.html";
    public static final String mGetInfoListUrl;
    public static final String mGetJINGYANDataUrl;
    public static final String mGetMessageListURL;
    public static String mGetNoteUrl = null;
    public static final String mGetShareUnlockBeiURL = "";
    public static final String mGetTokenDataUrl;
    public static final String mGetUserInfoUrl;
    public static final String mGet_user_score_info = "";
    public static final String mGetreplyMessageURL;
    public static final String mGoodsLocalUrl = "";
    public static final String mGoodsgetOrder;
    public static String mHospitalUrl = null;
    public static String mInfourl = null;
    public static final String mIsReadStatusUrl;
    public static final String mKefuTime;
    public static String mListSetUrl = null;
    public static final String mLoginUrl;
    public static final String mNoteURL;
    public static final String mOrderNewList;
    public static final String mOrderVerifyURL = "";
    public static final String mPostAnsweredURL;
    public static String mPostBatchUrl = null;
    public static final String mPostCollectionURL;
    public static final String mPostNoteURL;
    public static String mPutBianAdminDataUrl = null;
    public static String mPutComment = null;
    public static String mPutCommentUploadUrl = null;
    public static String mPutOpposeUrl = null;
    public static String mPutPraseUrl = null;
    public static final String mQuestionBeiURL;
    public static final String mQuestionCorrectionURL = "";
    public static final String mQuestionDataURL;
    public static String mQuestionSetUrl = null;
    public static final String mQuestionShareURL = "";
    public static String mRankingUrl = null;
    public static final String mRegisterCodeURL = "";
    public static String mRegisterNewUrl = null;
    public static final String mScore_list_tody = "";
    public static final String mShareDakaURL = "";
    public static final String mShareShipinClentUrl;
    public static final String mShareUnlockURL;
    public static String mShengfen = null;
    public static final String mSignDakaInfoURL = "";
    public static final String mSignDakaURL = "";
    public static String mSwitchAppUrl = null;
    public static String mTopicListApi = null;
    public static final String mUpdatePwdUrl;
    public static final String mUserDefaultAddress;
    public static String mWorkTimeUrl = null;
    public static final String mXiaohongshuCodeURL = "";
    public static String mYAnzheng;
    public static String mYComment;
    public static String mactiveurl;
    public static String majorUrl;
    public static String majorV2;
    public static final String mareaUrl;
    public static String mcollection;
    public static final String mcreateOrderUrl;
    public static final String meditUserAddressUrl;
    public static String memberServiceRule;
    public static final String messageCenter;
    public static String mexsearch;
    public static String mgetBatchUrl;
    public static final String mgetChapterPartUrl;
    public static final String mgetChapterUrl;
    public static String mgetList;
    public static final String mgetQuestionUrl;
    public static final String mgetUserAddressUrl;
    public static String mgetVideosUrl;
    public static String mineGetIconInfo;
    public static String minfoUrl;
    public static String missueApi;
    public static String mlabelUrl;
    public static String mmoreUrl;
    public static String mockShareUrl;
    public static final String mockStatisticsList;
    public static final String mockStatisticsOutlines;
    public static final String mockStatisticsStatInfo;
    public static final String morderFeeUrl;
    public static String moreApi;
    public static final String moveToQuestion;
    public static final String mquestionUpdateUrl;
    public static final String mredoList;
    public static String mremarkUrl;
    public static String mreportUrl;
    public static String msearchData;
    public static String msearchRankData;
    public static final String msetUserDefaultAddressUrl;
    public static final String msgUnredNumber;
    public static String mshareApi;
    public static String msubjecturl;
    public static String muserLabelUrl;
    public static String myAnalysisForQuestionApi;
    public static final String myCollectionList;
    public static String myCommentFilterUrl;
    public static String myCommentOriginApi;
    public static final String myCutQuestionList;
    public static final String myFileList;
    public static final String newHomeInfo;
    public static final String newHomeKingKongArea;
    public static final String newHomeTodayStatistics;
    public static final String nodeKnowledgeInfo;
    public static String noteFileApi;
    public static String noteUploads;
    public static String onBlackListApi;
    public static String orderCancel;
    public static String orderCouponList;
    public static String orderCouponListNew;
    public static String orderCourseReCommend;
    public static String orderDel;
    public static String orderDetail;
    public static String orderFeeAddrMultipleApi;
    public static String orderGiftItems;
    public static String orderRedPacketListNew;
    public static final String paperDetail;
    public static final String paperDetailNew;
    public static final String paperUserAnswer;
    public static String personalDayCouponsList;
    public static final String pointCount;
    public static String postArticle;
    public static String postforumselected;
    public static String proBookStackList;
    public static final String prospectusViewCount;
    public static final String pushNoteURL;
    public static final String putCourseComment;
    public static String qagreeApi;
    public static String qanalistApi;
    public static String qopposeApi;
    public static final String questionCategory;
    public static final String questionChartFilter;
    public static final String questionChartTree;
    public static final String questionCombineList;
    public static String questionInfoApi;
    public static final String questionKingKongArea;
    public static String questionListApi;
    public static final String questionRedo;
    public static String questionSetsList;
    public static final String questionTimeStatistics;
    public static String questionUserAnswerApi;
    public static String questionUserLabelApi;
    public static String questionVideoApi;
    public static String questionlabelApi;
    public static String rank2Api;
    public static String rank2Api2;
    public static final String rankShareUrl;
    public static String readHistoryList;
    public static final String receiveUserStudyPlan;
    public static final String recommendVideoList;
    public static final String recommendVideoSeeRecord;
    public static String recordPushLabelApi;
    public static String reddoturl;
    public static String redoAnswerApi;
    public static final String redoKnowledgeTree;
    public static final String redoOtherChapterList;
    public static final String redoStudyPlanQuestion;
    public static String removeBatchMemberApi;
    public static String removeBlackListApi;
    public static String removeManagerApi;
    public static String removeSingleMemberApi;
    public static String reportReason;
    public static String saveAdjustInfo;
    public static final String saveDelTargetSchool;
    public static final String schoolDetails;
    public static final String schoolMenuList;
    public static String searchArticleList;
    public static String searchHotTimes;
    public static String searchQuestionApi;
    public static final String searchSchoolOrMajor;
    public static final String serviceNotice;
    public static String setHiddenApi;
    public static String setJpushSeeTimeApi;
    public static final String setMessageNotice;
    public static final String settingErrorConfig;
    public static String shareArticle;
    public static final String shareGetCourse;
    public static final String shareHandout;
    public static final String sheetCutList;
    public static String shengYunRegister;
    public static final String shengYunShareInfo;
    public static String signToSign;
    public static String signinAds;
    public static String singleCommentFloorApi;
    public static String sourceReplyList;
    public static String soutceCommentDel;
    public static String soutceCommentList;
    public static String soutceCommentOppose;
    public static String soutceCommentReport;
    public static String soutceCommentSupport;
    public static String soutceStatusInfo;
    public static String statOneUrl;
    public static String statisticalChatInfoUrl;
    public static String statisticsShareUrl;
    public static String stockApi;
    public static final String studyPlanDrawUp;
    public static final String studyPlanInProgress;
    public static final String studyPlanNodeParams;
    public static final String studyPlanParams;
    public static final String studyPlanPlanConfig;
    public static final String studyPlanQuestionCount;
    public static final String studyPlanQuestionList;
    public static final String studyPlanRedoEveryTask;
    public static String studyReport;
    public static String subjectAnswerUrl;
    public static String subjectV2Api;
    public static String submitComment;
    public static final String submitCourseSurvey;
    public static String submitStatisticalApi;
    public static String submitStatisticalExamApi;
    public static final String submitVideoFeedBack;
    public static String tabList;
    public static final String targetSchoolSearchList;
    public static String touchShareUrl;
    public static String triggerApi;
    public static String unBannedMemberApi;
    public static final String unbindWx;
    public static String unboundEmail;
    public static String updateComment;
    public static String updateCommunityApi;
    public static String updateUserToEasemobApi;
    public static String uploadForComment;
    public static String useHelpCode;
    public static String userAgreementApi;
    public static String userCommentStatUrl;
    public static final String userDynamicInfo;
    public static final String userFeedback;
    public static final String userFeedbackInfo;
    public static final String userStudyPlanList;
    public static String verdetailApi;
    public static final String videoBasicInfo;
    public static final String videoBuryPoint;
    public static final String videoEvaluateList;
    public static final String videoHandoutList;
    public static final String videoQuestionInfo;
    public static final String videoSummary;
    public static final String videoSummaryQuestionRedo;
    public static String viewApi;
    public static String viewArticle;
    public static String vipApi;
    public static final String vipGetCourse;
    public static String vipNoticeApi;
    public static String vipToApi;
    public static String vipnoticeApi;
    public static String virtualUserReplyApi;
    public static String virtualUserReplyRedDotApi;
    public static String virtualUserUrl;
    public static String virtualUserWithReplyStatusApi;
    public static final String volRankStatus;
    public static String vote;
    public static String watchApi;
    public static String wcApi;
    public static String weekOrMonthReport;
    public static String wordBySearchKey;
    public static String CommentUrl = ProjectApp.instance().getCurrentEnvUrl();
    public static String CommentNewUrl = ProjectApp.instance().getCurrentEnvNewUrl();
    public static String CommentIameUrl = "https://ykb-app-files.yikaobang.com.cn/question/restore/";
    public static String CommentIameUrl2 = "https://ykb-app-files.yikaobang.com.cn/question/restore_2/";
    public static String commentH5Url = ProjectApp.instance().getCurrentEnvH5Url();

    static {
        String str = ProjectApp.instance().isConnectUrl() ? "https://ykb-exam-api.yikaobang.com.cn/" : "http://ykb-exam-test.yikaobang.com.cn/api/";
        EXAM_BASE_URL = str;
        mCommentIameUrl3 = "https://ykb-app-files.yikaobang.com.cn/question/question_set/";
        mAnsweredQuestionURL = CommentUrl + "Question/Answer/getBatch";
        mClearAnsweredURL = CommentUrl + "question/answer/cleanUserAnswerV3";
        mPostAnsweredURL = CommentUrl + "Question/Answer/postBatchForAll";
        mredoList = CommentUrl + "/question/answer/redov3";
        mPostNoteURL = CommentUrl + "Question/Note/postBatchForAll";
        pushNoteURL = CommentUrl + "allQuestion/Note/pushNote";
        getNoteURL = CommentUrl + "allQuestion/Note/getNote";
        cleanNoteURL = CommentUrl + "allQuestion/Note/cleanNote";
        errorCorrectionListURL = CommentUrl + "allQuestion/ErrorCorrection/getList";
        errorCorrectionNewListURL = CommentUrl + "/allQuestion/ErrorCorrection/getListv2";
        errorCorrectionSaveURL = CommentUrl + "allQuestion/ErrorCorrection/save";
        errorCorrectionPraiseURL = CommentUrl + "allQuestion/ErrorCorrection/praise";
        errorCorrectionGettypeURL = CommentUrl + "allQuestion/ErrorCorrection/gettype";
        errorCorrectionReplyListURL = CommentUrl + "allQuestion/ErrorCorrection/getReplyList";
        getCorrectionRulesURL = CommentUrl + "allQuestion/ErrorCorrection/getCorrectionRules";
        columnSortURL = CommentUrl + "/allQuestion/question/columnSort";
        mNoteURL = CommentUrl + "Question/Note/getBatch";
        mClearNoteURL = CommentUrl + "Question/Note/cleanBatch";
        mCourseAddNoteURL = CommentUrl + "curriculum/main/putNote";
        mCourseClearNoteURL = CommentUrl + "curriculum/main/removeNote";
        mCourseNoteListURL = CommentUrl + "curriculum/main/note";
        mCollectionURL = CommentUrl + "Question/Collection/getBatch";
        mPostCollectionURL = CommentUrl + "Question/Collection/postBatchForAll";
        mClearCollectionURL = CommentUrl + "Question/Collection/cleanBatch";
        mChatFollowlist = CommentUrl + "Chat/Chat/followList";
        mChatFollow = CommentUrl + "Chat/Chat/follow";
        mChatUnFollow = CommentUrl + "Chat/Chat/unFollow";
        mChatGetToken = CommentUrl + "Chat/Chat/getToken";
        shengYunShareInfo = CommentUrl + "Activity/main/getShengYunActivity";
        mCommentList = CommentUrl + "Comment/Main/list";
        mPutComment = CommentUrl + "Comment/Main/publish";
        courseCommentList = CommentNewUrl + "course/main/evaluate/list";
        putCourseComment = CommentNewUrl + "course/main/evaluate/publish";
        mPutPraseUrl = CommentUrl + "Comment/Main/praise";
        mPutOpposeUrl = CommentUrl + "Comment/Main/oppose";
        mGetCommentReplyUrl = CommentUrl + "Comment/Main/getCommentReply";
        mDeleteUrl = CommentUrl + "Comment/Main/delete";
        mYComment = CommentUrl + "Comment/Main/myComment";
        mDigest = CommentUrl + "Comment/Main/digest";
        mYAnzheng = CommentUrl + "User/Main/authCode";
        authCodeEmail = CommentUrl + "user/main/authCodeEmail";
        confirmVerifyCode = CommentUrl + "user/main/verifyCode";
        changeEmail = CommentUrl + "user/main/changeEmail";
        unboundEmail = CommentUrl + "user/main/unboundEmail";
        mShengfen = CommentUrl + "User/Info/school";
        majorUrl = CommentUrl + "User/Info/major";
        majorV2 = CommentUrl + "user/info/majorV2";
        getEntranceTimeApi = CommentUrl + "user/info/getEntranceTime";
        mRegisterNewUrl = CommentUrl + "User/Main/register";
        mAvatar2URL = CommentUrl + "User/Main/avatar";
        mLoginUrl = CommentUrl + "User/Main/login";
        checkChangeNickname = CommentUrl + "user/main/checkChangeNickname";
        changeUserInfo = CommentUrl + "user/main/changeUserInfo";
        changeMobile = CommentUrl + "user/main/changeMobile";
        mUpdatePwdUrl = CommentUrl + "User/Main/updatePwd";
        accessLogUrl = CommentUrl + "user/main/accessLog";
        mAdUrl = CommentUrl + "Client/Main/startPage";
        mAddUsortUrl = CommentUrl + "experience/articlev2/addUserCategorySort";
        mGetInfoListUrl = CommentUrl + "experience/articlev2/getInfoList";
        mAddCollectionUrl = CommentUrl + "experience/article/addCollection";
        mAddShareUrl = CommentUrl + "experience/article/addShare";
        mAddCommentShareUrl = CommentUrl + "experience/article/addCommentShare";
        mIsReadStatusUrl = CommentUrl + "experience/article/addRead";
        mGetJINGYANDataUrl = CommentUrl + "experience/article/getArticleStatus";
        mGetUserInfoUrl = CommentUrl + "User/Main/getUserInfo";
        mgetChapterUrl = CommentUrl + "Question/Main/getChapter";
        mgetChapterPartUrl = CommentUrl + "Question/Main/getPart";
        mgetQuestionUrl = CommentUrl + "Question/Main/getQuestion";
        mquestionUpdateUrl = CommentUrl + "Question/Main/questionUpdate";
        mQuestionBeiURL = CommentUrl + "Question/Exampoints/getList";
        mShareUnlockURL = CommentUrl + "client/main/share";
        mShareShipinClentUrl = CommentUrl + "Share/Main/share";
        mQuestionDataURL = CommentUrl + "Question/Main/stat";
        mCheckVersionUrl = CommentUrl + "version/version/check";
        appTestVersionInfo = CommentUrl + "version/version/betaOpen";
        mGetTokenDataUrl = CommentUrl + "User/Main/getTokenSecret";
        mFeedUrl = CommentUrl + "client/main/feedback";
        mHospitalUrl = CommentUrl + "user/info/hospital";
        mDepartmentUrl = CommentUrl + "user/info/department";
        mWorkTimeUrl = CommentUrl + "user/info/getWorkTime";
        mSwitchAppUrl = CommentUrl + "User/Main/switchApp";
        mCourseVideoDaka = CommentUrl + "Course/Course/clock";
        mCoursePlayNum = CommentUrl + "course/course/see";
        mGetCourse = CommentUrl + "course/course/getCourse";
        goodsCategoryUrl = CommentUrl + "Shop/Main/goodsCategory";
        goodsCategory = CommentNewUrl + "shop/main/goodsCategory";
        goodsListUrl = CommentUrl + "Shop/Main/goodsList";
        goodsList = CommentNewUrl + "shop/main/goodsList";
        goodsSearch = CommentNewUrl + "shop/main/search";
        goodsDetailURL = CommentUrl + "Shop/Main/goodsDetail";
        goodsDetailNewURL = CommentNewUrl + "shop/main/goodsDetail";
        mcreateOrderUrl = CommentNewUrl + "shop/main/createOrderAddrMultiple";
        mUserDefaultAddress = CommentUrl + "Shop/Main/userDefaultAddress";
        mareaUrl = CommentUrl + "Shop/Main/area";
        meditUserAddressUrl = CommentNewUrl + "shop/main/editUserAddress";
        mgetUserAddressUrl = CommentNewUrl + "shop/main/getUserAddress";
        msetUserDefaultAddressUrl = CommentUrl + "Shop/Main/setUserDefaultAddress";
        morderFeeUrl = CommentNewUrl + "shop/main/orderFeeAddrMultiple";
        goodsDetailHtmlUrl = CommentUrl + "Shop/Main/goodsDetailHtml";
        mKefuTime = CommentUrl + "Shop/Main/customerServiceOnline";
        mOrderNewList = CommentNewUrl + "shop/main/userOrders";
        mGoodsgetOrder = CommentUrl + "v2/Shop/Main/userOrdersDetail";
        mPutCommentUploadUrl = CommentUrl + "Stock/File/upload";
        mPutBianAdminDataUrl = CommentUrl + "Comment/Main/update";
        virtualUserUrl = CommentUrl + "User/Backstage/virtualUser";
        mGetMessageListURL = CommentUrl + "client/message/list";
        mGetreplyMessageURL = CommentUrl + "comment/unified/replyMessage";
        addOrCancel = CommentUrl + "Course/Collection/addOrCancel";
        getNoteurl = CommentUrl + "Course/Note/getNote";
        getVideos = CommentUrl + "Question/Video/getVideos";
        getH5ShareUrl = CommentUrl + "experience/article/getH5Share";
        myCommentFilterUrl = CommentUrl + "question/main/listStand";
        mCommlogUrl = "http://share.yikaobang.com.cn/comment/comment.html";
        mBanUrl = CommentUrl + UrlConfigKt.ACCOUNT_BANNED;
        mreportUrl = CommentUrl + "User/Behavior/report";
        mlabelUrl = CommentUrl + "Question/Main/label";
        muserLabelUrl = CommentUrl + "Question/Main/userLabel";
        mremarkUrl = CommentUrl + "Question/Evaluation/remark";
        mEsexUrl = CommentUrl + "exam/main/list";
        mRankingUrl = CommentUrl + "exam/main/ranking";
        mPostBatchUrl = CommentUrl + "exam/answer/postBatch";
        mgetBatchUrl = CommentUrl + "exam/answer/getBatch";
        statOneUrl = CommentUrl + "exam/main/statOne";
        minfoUrl = CommentUrl + "exam/main/info";
        mgetVideosUrl = CommentUrl + "exam/video/getVideos";
        mactiveurl = CommentUrl + "exam/main/active";
        uploadForComment = CommentUrl + UrlConfigKt.UPLOAD_FORCOMMENT;
        noteUploads = CommentUrl + "allQuestion/Note/uploads";
        circleReport = CommentUrl + "bbs/Article/report";
        reportReason = CommentUrl + UrlConfigKt.COMMENT_REPORT_REASON;
        stockApi = CommentUrl + "stock/File/put";
        addArticle = CommentUrl + "bbs/article/addArticle";
        editArticle = CommentUrl + "bbs/article/editArticle";
        mgetList = CommentNewUrl + "bbs/category/list";
        getArticleList = CommentUrl + "bbs/article/getArticleList";
        getArticleInfo = CommentNewUrl + "bbs/article/getArticleInfo";
        getParentCate = CommentUrl + "bbs/Category/getParentCate";
        vote = CommentUrl + "bbs/article/vote";
        addUserCategorySort = CommentUrl + "bbs/category/addUserCategorySort";
        interAction = CommentUrl + "bbs/article/interAction";
        mcollection = CommentUrl + "bbs/article/collection";
        msearchData = CommentUrl + "bbs/article/search";
        viewArticle = CommentUrl + "bbs/article/viewArticle";
        mCommentShareInfo = CommentUrl + "experience/article/getCommentShareInfo";
        mexsearch = CommentUrl + "experience/article/search";
        handout_comment_search = CommentUrl + "/comment/main/search";
        deleTieziUrl = CommentUrl + "bbs/article/delArticle";
        mshareApi = CommentUrl + "Activity/main/share";
        reddoturl = CommentUrl + "comment/unified/reddot";
        getCourseDataurl = CommentUrl + "course/course/getCourseAk";
        subjectAnswerUrl = CommentUrl + "Question/Answer/subjectAnswer";
        msubjecturl = CommentUrl + "question/subject/question";
        mCategoryListNewUrl = CommentUrl + "experience/articlev2/getCategoryList";
        getSortListUrl = CommentUrl + "experience/articlev2/getSortList";
        mListSetUrl = CommentUrl + "allquestion/sets/categoryList";
        mExamListSetUrl = CommentUrl + "allquestion/sets/examCategoryList";
        mExamListSetMoreUrl = CommentUrl + "allquestion/sets/moreExam";
        mCollectSetUrl = CommentUrl + "question/sets/collect";
        mQuestionSetUrl = CommentUrl + "question/sets/question";
        mGetNoteUrl = CommentUrl + "Question/Note/getNote";
        mmoreUrl = CommentUrl + "allquestion/sets/more";
        userCommentStatUrl = CommentUrl + "Comment/Main/userCommentStat";
        mInfourl = CommentUrl + "allquestion/sets/info";
        gradeformApi = CommentUrl + "exam/volExam/form";
        gradeformRankApi = CommentUrl + "exam/volunteer/form";
        gradeApi = CommentUrl + "exam/volunteer/grade";
        gradeApi2 = CommentUrl + "exam/volExam/volunteer";
        rank2Api = CommentUrl + "exam/volunteer/rank";
        rank2Api2 = CommentUrl + "/exam/volExam/rank";
        vipApi = CommentUrl + "v2/activity/main/listAndUserPermission";
        chapterLockApi = CommentUrl + "activity/main/chapterLock";
        vipToApi = CommentUrl + "user/main/vip";
        follerListApi = CommentUrl + "User/Main/follerList";
        viewApi = CommentUrl + "bbs/article/view";
        courselistApi = CommentUrl + "vidteaching/main/list";
        chapterApi = CommentUrl + "vidteaching/main/chapter";
        coursevideoApi = CommentUrl + "vidteaching/main/video";
        collectApi = CommentUrl + "vidteaching/main/collect";
        infoApi = CommentUrl + "vidteaching/main/info";
        watchApi = CommentUrl + "vidteaching/main/watch";
        getNoteApi = CommentUrl + "vidteaching/note/get";
        addNoteApi = CommentUrl + "vidteaching/note/add";
        handleWatchedApi = CommentUrl + "vidteaching/main/handleWatched";
        collectVideoApi = CommentUrl + "vidteaching/main/collectVideo";
        moreApi = CommentUrl + "vidteaching/main/more";
        orderFeeAddrMultipleApi = CommentNewUrl + "shop/main/orderFeeAddrMultiple";
        getNoticeApi = CommentUrl + "jpush/list/getNotice";
        setJpushSeeTimeApi = CommentUrl + "jpush/list/setJpushSeeTime";
        editReceivingAddressApi = CommentNewUrl + "shop/main/editReceivingAddress";
        exchangelistApi = CommentUrl + "shop/cdkey/list";
        exchangecodeApi = CommentUrl + "shop/cdkey/exchange";
        vipnoticeApi = CommentUrl + "client/main/notice";
        vipNoticeApi = CommentUrl + "client/main/vipNotice";
        noteFileApi = ProjectApp.instance().isConnectUrl() ? "https://ykb-app-service.yikaobang.com.cn/note/export" : "http://test.ykb-app-service.yikaobang.com.cn/note/export";
        wcApi = ProjectApp.instance().isConnectUrl() ? "https://ykb-app-service.yikaobang.com.cn/question/export" : "http://ykb-app-exporter-test.yikaobang.com.cn:18888/question/export";
        editorLikesApi = CommentUrl + "bbs/article/editorLikes";
        myAnalysisForQuestionApi = CommentUrl + "question/analysis/myAnalysisForQuestion";
        qopposeApi = CommentUrl + "question/analysis/oppose";
        qagreeApi = CommentUrl + "question/analysis/agree";
        qanalistApi = CommentUrl + "question/analysis/list";
        setHiddenApi = CommentUrl + "question/analysis/setHidden";
        homePageSmallAdApi = CommentUrl + "client/main/ads";
        adsInCommentApi = CommentUrl + "client/main/adsInComment";
        commsearchApi = CommentUrl + "comment/main/search";
        commenthotApi = CommentUrl + "comment/main/hot";
        singleCommentFloorApi = CommentUrl + "comment/main/singleCommentFloor";
        cancellationApi = CommentUrl + "user/main/cancellation";
        getCourseNewApi = CommentUrl + "course/courseV2/getCourse";
        getCourseAkApi = CommentUrl + "Course/CourseV2/getCourseAk";
        getGroupCodeApi = CommentUrl + "Course/CourseV2/getGroupCode";
        getPrivacyApi = "https://api.yikaobang.com.cn/app/privacy.html";
        userAgreementApi = "https://api.yikaobang.com.cn/app/user-agreement.html";
        memberServiceRule = "https://api.yikaobang.com.cn/app/vipAgreement.html";
        questionInfoApi = CommentUrl + "allquestion/question/info";
        questionListApi = CommentUrl + "allquestion/question/list";
        getSourceInfoById = CommentUrl + "allQuestion/question/videoAudio";
        questionUserAnswerApi = CommentUrl + "allquestion/main/userAnswer";
        questionVideoApi = CommentUrl + "allquestion/question/video";
        questionlabelApi = CommentUrl + "allquestion/main/label";
        questionUserLabelApi = CommentUrl + "allquestion/main/userLabel";
        adminUpdateLabelCountApi = CommentUrl + "allQuestion/main/adminUpdateLabelCount";
        clearAnswerApi = CommentUrl + "allquestion/main/clearAnswer";
        redoAnswerApi = CommentUrl + "allquestion/main/redoAnswer";
        submitStatisticalApi = CommentUrl + "allquestion/main/submitStatistical";
        submitStatisticalExamApi = CommentUrl + "exam/main/submitStatistical";
        getchapterApi = CommentUrl + "allquestion/question/chapter";
        getstatApi = CommentUrl + "allquestion/main/stat";
        getanswerApi = CommentUrl + "Question/Answer/postBatchForAll";
        getWordInfoApi = CommentUrl + "allquestion/word/getinfo";
        getcollectionApi = CommentUrl + "Question/Collection/postBatchForAll";
        cleancollectionApi = CommentUrl + "Question/Collection/cleanBatch";
        getnoteApi = CommentUrl + "Question/Note/getNote";
        getpostNoteApi = CommentUrl + "Question/Note/postBatchForAll";
        clearNoteApi = CommentUrl + "Question/Note/cleanBatch";
        getmyAnalysisApi = CommentUrl + "question/analysis/myAnalysisForQuestion";
        getallAnalysisApi = CommentUrl + "question/analysis/list";
        getsaveAnalysisApi = CommentUrl + "question/analysis/add";
        getforumindexApi = CommentUrl + "group/main/list";
        getforumchildrenApi = CommentUrl + "group/main/children";
        postforumselected = CommentUrl + "group/main/selected";
        getforumfollowApi = CommentUrl + "group/main/follow";
        getforumdetailApi = CommentUrl + "group/main/detail";
        getforumauthenticationApi = CommentUrl + "/user/main/authentication";
        getforumlabellistApi = CommentUrl + "group/category/list";
        getforumlistApi = CommentUrl + "group/article/list";
        getforumDetailInfoApi = CommentUrl + "group/article/detail";
        getforumDDeteleInfoApi = CommentUrl + "group/article/delete";
        getforumDCollectionInfoApi = CommentUrl + "group/article/collection";
        getforumDpraiseInfoApi = CommentUrl + "group/article/praise";
        getforumvoteApi = CommentUrl + "group/article/vote";
        getforumeditPraiseApi = CommentUrl + "group/article/editPraise";
        getforumviewApi = CommentUrl + "group/article/view";
        getforumpostingApi = CommentUrl + "group/article/posting";
        getforumTopApi = CommentUrl + "group/main/top";
        getforummemberApi = CommentUrl + "group/main/member";
        getforumeditIntroductionApi = CommentUrl + "group/main/editIntroduction";
        getforumeexitApi = CommentUrl + "group/main/exit";
        getforumrecordingTimeApi = CommentUrl + "group/main/recordingTime";
        getforumsearchDataApi = CommentUrl + "group/article/search";
        getforumuploadImageApi = CommentUrl + "group/main/uploadImage";
        getforumgroupApi = CommentUrl + "group/main/index";
        subjectV2Api = CommentUrl + "allQuestion/question/subjectV2";
        getIdentityLabel = CommentUrl + "allQuestion/question/getIdentityLabel";
        questionSetsList = CommentUrl + "allQuestion/sets/list";
        getIdentityChapter = CommentUrl + "allQuestion/sets/chapter";
        getUserTypeApi = CommentUrl + "User/Main/getUserType";
        getUserEducationApi = CommentUrl + "User/Main/getUserEducation";
        getUserInfoApi = CommentUrl + "User/Main/getUserInfo";
        getactiveApi = CommentUrl + "group/main/active";
        getgiveLogApi = CommentUrl + "group/main/giveLog";
        myCommentOriginApi = CommentUrl + "Comment/Main/myCommentOrigin";
        searchQuestionApi = CommentUrl + "allquestion/question/searchQuestion";
        chatCategoryApi = CommentUrl + "chat/community/category";
        chatListApi = CommentUrl + "chat/community/list";
        chatJoinApi = CommentUrl + "chat/community/join";
        chatSignOutApi = CommentUrl + "chat/community/signOut";
        chatDetailApi = CommentUrl + "chat/community/detail";
        chatAnnouncementApi = CommentUrl + "chat/community/announcement";
        chatMemberApi = CommentUrl + "chat/community/member";
        onBlackListApi = CommentUrl + "chat/chat/onBlackList";
        addBlackListApi = CommentUrl + "chat/chat/addBlackList";
        removeBlackListApi = CommentUrl + "chat/chat/removeBlackList";
        updateCommunityApi = CommentUrl + "chat/community/updateCommunity";
        removeSingleMemberApi = CommentUrl + "chat/community/removeSingleMember";
        removeBatchMemberApi = CommentUrl + "chat/community/removeBatchMember";
        chatRecordingTimeApi = CommentUrl + "chat/community/recordingTime";
        getAnnouncementApi = CommentUrl + "chat/community/getAnnouncement";
        communitySeeApi = CommentUrl + "chat/community/see";
        addManagerApi = CommentUrl + "chat/community/addManager";
        removeManagerApi = CommentUrl + "chat/community/removeManager";
        bannedSingleMemberApi = CommentUrl + "chat/community/bannedSingleMember";
        unBannedMemberApi = CommentUrl + "chat/community/unBannedMember";
        recordPushLabelApi = CommentUrl + "client/main/recordPushLabel";
        updateUserToEasemobApi = CommentUrl + "chat/chat/updateUserToEasemob";
        communityCategoryApi = CommentUrl + "chat/community/category";
        commentRuleApi = CommentUrl + "comment/main/commentRule";
        listWithRuleApi = CommentUrl + "comment/main/listWithRule";
        mTopicListApi = CommentUrl + "bbs/topic/list";
        mCustomTopicListApi = CommentUrl + "bbs/topic/custom";
        clearAllAnswerNoticeApi = CommentUrl + "allQuestion/main/clearAllAnswerNotice";
        clearAllAnswerApi = CommentUrl + "allQuestion/main/clearAllAnswer";
        liveCalendarLiveDate = CommentNewUrl + "course/liveCalendar/liveDate";
        liveCalendarLiveDataList = CommentNewUrl + "course/liveCalendar/liveList";
        courseCourseSpecial = CommentNewUrl + "course/main/special";
        courseSpecialList = CommentNewUrl + "course/main/specialList";
        courseLearnCenterDay = CommentNewUrl + "course/center/stat";
        courseLearnCenterList = CommentNewUrl + "course/center/list";
        courseDirectoryTab = CommentNewUrl + "course/center/tab";
        courseDirectoryCombine = CommentNewUrl + "course/center/catalogue";
        courseDirectoryCollect = CommentNewUrl + "course/center/collection";
        courseDirectoryNote = CommentNewUrl + "course/center/note";
        courseQRCode = CommentNewUrl + "course/center/qrcode";
        courseJIANG_YI = CommentNewUrl + "course/center/handout";
        courseBannerLiving = CommentNewUrl + "course/main/liveRecommend";
        courseCategoryTab = CommentNewUrl + "course/main/courseCategory";
        courseMainList = CommentNewUrl + "course/main/courseList";
        courseMainListSearch = CommentNewUrl + "course/main/search";
        orderCancel = CommentNewUrl + "shop/order/cancel";
        orderDel = CommentNewUrl + "shop/order/del";
        orderCourseReCommend = CommentNewUrl + "course/main/courseRecommend";
        orderCouponList = CommentNewUrl + "shop/privilege/list";
        orderCouponListNew = CommentNewUrl + "shop/order/userCoupon";
        orderRedPacketListNew = CommentNewUrl + "shop/order/userRedPacket";
        orderDetail = CommentNewUrl + "shop/main/userOrdersDetailNew";
        courseNoteExport = ProjectApp.instance().isConnectUrl() ? "https://ykb-app-service.yikaobang.com.cn/courseNote/export" : "http://test.ykb-app-service.yikaobang.com.cn/courseNote/export";
        orderGiftItems = CommentNewUrl + "course/main/giftItems";
        knowledgeTaskList = CommentNewUrl + "knowledge/task/list";
        getKnowledgeTask = CommentNewUrl + "knowledge/task/receiveReward";
        tabList = CommentNewUrl + "question/category/list";
        knowledgeList = CommentNewUrl + "question/knowledgeTreeAndDetail";
        knowledgeList_zz_zt = CommentNewUrl + "knowledge/paperCategory/chapterList";
        dailyTaskData = CommentNewUrl + "studyPlan/userStudyPlan/everyTaskList";
        dailyUpdateTime = CommentNewUrl + "studyPlan/userStudyPlan/updateNoticeTime";
        dailyDataByDate = CommentNewUrl + "studyPlan/userStudyPlan/everyTaskPart";
        dailyTaskReset = CommentNewUrl + "studyPlan/userStudyPlan/redoEveryTask";
        curriculumCategroyUrl = CommentUrl + "curriculum/category/list";
        curriculumListUrl = CommentUrl + "curriculum/main/list";
        curriculumdetailUrl = CommentUrl + "curriculum/main/detail";
        curriculummyCollectionUrl = CommentUrl + "curriculum/main/myCollection";
        curriculummyNoteUrl = CommentUrl + "curriculum/main/myNote";
        curriculummyCommentUrl = CommentUrl + "curriculum/main/myComment";
        curriculumstateUrl = CommentUrl + "curriculum/main/state";
        curriculumcollectUrl = CommentUrl + "curriculum/main/collect";
        curriculumseeUrl = CommentUrl + "curriculum/main/see";
        curriculumtryAndSeeUrl = CommentUrl + "curriculum/main/tryAndSee";
        missueApi = CommentUrl + "issue/Main/list";
        isscategoryUrl = CommentUrl + "issue/Main/category";
        issdetailUrl = CommentUrl + "issue/Main/detail";
        kefucsApi = CommentUrl + "issue/Main/cs";
        triggerApi = CommentUrl + "curriculum/main/trigger";
        verdetailApi = CommentUrl + "vidteaching/main/detail";
        courseDetailInfo = CommentNewUrl + "course/main/info";
        buyInfoV2Api = CommentUrl + "shop/vip/buyInfoV2";
        virtualUserWithReplyStatusApi = CommentUrl + "comment/unified/virtualUserWithReplyStatus";
        virtualUserReplyApi = CommentUrl + "comment/unified/virtualUserReply";
        virtualUserReplyRedDotApi = CommentUrl + "comment/unified/virtualUserReplyRedDot";
        getInputInviteCodeURL = CommentUrl + "User/Main/inviteCode";
        getInvitePageURL = CommentUrl + "User/Main/invitePage";
        getInviteListUrl = CommentUrl + "User/Main/inviteList";
        USER_EXAM = str + "api/question/getUserExam";
        GET_EXAM_INFO = str + "api/question/getExam";
        GET_USER_ANSWER_RECORD = str + "api/question/getUserAnswer";
        SUBMIT_ANSWER_RECORD = str + "api/question/answer";
        GET_QUESTION = str + "api/question/getQuestion";
        EXAM_RANKING = str + "api/question/getRankList";
        COMMENT_TEMP_POINT = CommentUrl + "Comment/Main/temporaryPoint";
        QUESTION_AD_CONFIG = CommentUrl + "Config/Configure/getMoreConfig";
        QUESTION_EXPOSE = CommentUrl + "/allQuestion/Main/questionExposureCountForDate";
        CHANNEL_LIST = CommentUrl + "user/channel/list";
        SUBMIT_CHANNEL = CommentUrl + "user/channel/send";
        settingErrorConfig = CommentUrl + "/User/ErrorSetting/changeSetting";
        messageCenter = CommentUrl + "notice/main/index";
        pointCount = CommentUrl + "Point/Main/pointCount";
        userDynamicInfo = CommentUrl + "User/Statistics/index";
        userFeedbackInfo = CommentUrl + "notice/main/feedback";
        bindWx = CommentUrl + "User/Socialite/bindForUser";
        combinePaperColumn = CommentUrl + "papers/main/paperColumn";
        combineQuestionFilterOptions = CommentUrl + "papers/main/getPaperOptions";
        checkSocialLoginBind = CommentUrl + "User/Socialite/bindList";
        WxLogin = CommentUrl + "User/Socialite/login";
        bindMobileLogin = CommentUrl + "User/Socialite/bindForMobile";
        combineQuestion = CommentUrl + "papers/main/makePaper";
        unbindWx = CommentUrl + "User/Socialite/unbind";
        blackList = CommentUrl + "chat/chat/getBlackList";
        serviceNotice = CommentUrl + "notice/service/index";
        getClassNotice = CommentUrl + "notice/live/index";
        getPraiseNoticeList = CommentUrl + "notice/main/praise";
        cleanUnredNumberMsg = CommentUrl + "notice/main/clear";
        questionCombineList = CommentUrl + "papers/main/myPaper";
        deleteCombineQuestion = CommentUrl + "papers/main/delPaper";
        paperDetail = CommentUrl + "papers/main/paperList";
        paperDetailNew = CommentNewUrl + "knowledge/paper/paperList";
        recommendVideoSeeRecord = CommentNewUrl + "knowledge/detail/videoSee";
        paperUserAnswer = CommentUrl + "papers/main/paperUserAnswer";
        getMessageNotice = CommentUrl + "notice/main/messageSetting";
        setMessageNotice = CommentUrl + "notice/main/changeMessageSetting";
        msgUnredNumber = CommentUrl + "notice/Main/reddot";
        deleteUserAddress = CommentNewUrl + "shop/main/deleteUserAddress";
        chooseChapter = CommentUrl + "papers/main/chapterList";
        combineRedo = CommentUrl + "papers/main/redoAnswer";
        questionRedo = CommentUrl + "allquestion/main/redoAnswerWithWrong";
        cutQuestion = CommentUrl + "/allQuestion/cutQuestion/cut";
        myCutQuestionList = CommentUrl + "allQuestion/cutQuestion/cutChapter";
        moveToQuestion = CommentUrl + "allQuestion/cutQuestion/moveBack";
        sheetCutList = CommentUrl + "allQuestion/cutQuestion/cutList";
        redoOtherChapterList = CommentUrl + "allquestion/question/redoChapter";
        buyFilePermission = CommentUrl + "bbs/article/enclosurePermissionList";
        myFileList = CommentUrl + "bbs/article/myArticleEnclosureList";
        joinAppTest = CommentUrl + "user/main/signUpBetaTest";
        appTestFeedBack = commentH5Url + "feedback.html";
        appTestInfo = commentH5Url + "sginUp.html";
        getReplyCommentCount = CommentUrl + "Comment/Main/commentCount";
        getComputerRuleInfo = CommentUrl + "Exam/main/examDescription";
        getComputerStatisticsInfo = CommentUrl + "Exam/main/statForComputerTest";
        getJobList = CommentUrl + "User/info/hospitalPosition";
        getInformationList = CommentNewUrl + "source/file/folderFileList";
        downloadFileCount = CommentNewUrl + "source/file/downloadCount";
        getAppProject = CommentNewUrl + "source/file/appStatistics";
        infoCollection = CommentNewUrl + "source/file/collect";
        soutceStatusInfo = CommentNewUrl + "source/file/info";
        submitComment = CommentNewUrl + "source/review/addReview";
        soutceCommentList = CommentNewUrl + "source/review/getList";
        soutceCommentOppose = CommentNewUrl + "source/review/oppose";
        soutceCommentSupport = CommentNewUrl + "source/review/agree";
        soutceCommentDel = CommentNewUrl + "source/review/delReview";
        soutceCommentReport = CommentNewUrl + "source/review/report";
        updateComment = CommentNewUrl + "source/review/editReview";
        sourceReplyList = CommentNewUrl + "source/review/getReply";
        hotCircle = CommentNewUrl + "bbs/main/hotBbs";
        forumTopData = CommentNewUrl + "bbs/main/bbsTopView";
        bookStackList = CommentNewUrl + "ebook/book/appStatistics";
        proBookStackList = CommentNewUrl + "ebook/book/folderBookList";
        bookList = CommentNewUrl + "ebook/bookshelf/bookList";
        readHistoryList = CommentNewUrl + "ebook/bookshelf/readHistory";
        addBook = CommentNewUrl + UrlConfigKt.ADD_BOOK;
        delHistoryRecord = CommentNewUrl + "ebook/bookshelf/delReadHistory";
        delBook = CommentNewUrl + UrlConfigKt.DEL_BOOK;
        forumSearchCategoryData = CommentNewUrl + "bbs/search/searchModule";
        forumSearchCategoryFilterData = CommentNewUrl + "bbs/search/searchOption";
        msearchRankData = CommentNewUrl + "bbs/article/searchRanking";
        wordBySearchKey = CommentNewUrl + "bbs/article/searchLogMate";
        articleList = CommentNewUrl + "bbs/article/list";
        searchArticleList = CommentNewUrl + "bbs/search/list";
        postArticle = CommentNewUrl + "bbs/article/add";
        editArticleNew = CommentNewUrl + "bbs/article/edit";
        shareArticle = CommentUrl + "bbs/article/shareCountRecord";
        getForumBottomStatus = CommentNewUrl + "bbs/main/stat";
        getPraiseRankList = CommentNewUrl + "ranking/praise/statisticsList";
        getCommentRankList = CommentNewUrl + "ranking/comment/statisticsList";
        getPostRankList = CommentNewUrl + "ranking/bbsArticle/statisticsList";
        getDoQuetionRankList = CommentNewUrl + "user/getUserSheetStatistics";
        getContinuousActiveRankList = CommentNewUrl + "user/loginContinueTotal";
        getAccumulateActiveRankList = CommentNewUrl + "user/loginTotal";
        getAllRankInfo = CommentNewUrl + "user/getUserCharts";
        getStatisticalTab = CommentNewUrl + "userSheet/getIdentityInfo";
        getStatisticalTopData = CommentNewUrl + "userBrushingQuestionStatistics/getSheetHistoryAndAnswerInfo";
        getStatisticalRankData = CommentNewUrl + "userBrushingQuestionStatistics/getUserRank";
        getStatisticalPercentInfo = CommentNewUrl + "userBrushingQuestionStatistics/getTodaySheetInfo";
        getTodayStatisticalData = CommentNewUrl + "userSheet/getTodaySheetInfo";
        getQuestionAndUnitSheet = CommentNewUrl + "userSheet/getQuestionAndUnitSheet";
        statisticalChatInfoUrl = commentH5Url;
        infoUrl = "https://filepreview.kaoyanhui.com.cn/";
        searchHotTimes = CommentNewUrl + "bbs/main/bbsExpSearchTotal";
        getForumHotRank = CommentNewUrl + "bbs/main/bbsExpHotList";
        infomationShareCount = CommentNewUrl + "source/file/shareCount";
        anonymousPushCircleConfig = CommentNewUrl + "/bbs/main/appIsAnonymous";
        myCollectionList = CommentNewUrl + "source/file/collectList";
        delCollection = CommentNewUrl + "source/file/delCollect";
        getCircleAccess = CommentNewUrl + "bbs/article/getArticleNoAccess";
        getShareTask = CommentNewUrl + "user/task/userTask";
        videoBuryPoint = CommentNewUrl + "course/main/watchDuration";
        courseDetail = CommentNewUrl + "course/main/detail";
        courseStructure = CommentNewUrl + "course/main/coursePackage";
        courseUnlock = CommentNewUrl + "course/main/listAndUserPermission";
        courseSurveyList = CommentNewUrl + "course/questionnaire/info";
        submitCourseSurvey = CommentNewUrl + "course/questionnaire/submit";
        getFreeCourse = CommentNewUrl + "course/main/getFreeCourse";
        shareGetCourse = CommentNewUrl + "course/main/getShareCourse";
        videoSummary = CommentNewUrl + "course/video/summary";
        videoHandoutList = CommentNewUrl + "course/video/handout";
        videoBasicInfo = CommentNewUrl + "course/video/info";
        vipGetCourse = CommentNewUrl + "course/main/getVipCourse";
        videoEvaluateList = CommentNewUrl + "course/video/evaluateList";
        submitVideoFeedBack = CommentNewUrl + "course/video/saveFeedback";
        userFeedback = CommentNewUrl + "course/video/userFeedback";
        courseVideoCollect = CommentNewUrl + "course/video/collect";
        courseVideoNoteList = CommentNewUrl + "course/video/noteList";
        courseVideoAddNote = CommentNewUrl + "course/video/saveNote";
        deleteVideoNote = CommentNewUrl + "course/video/delNote";
        liveHandout = CommentNewUrl + "course/main/liveHandout";
        gfRanking = CommentUrl + "exam/main/gfRanking";
        departmentSchool = CommentUrl + "User/School/departmentSchool";
        departmentMajor = CommentUrl + "User/School/departmentMajor";
        departmentMajorDirection = CommentUrl + "User/School/departmentMajorDirection";
        volRankStatus = CommentUrl + "exam/volunteer/rankInfo";
        getSchoolMajor = CommentUrl + "User/School/schoolMajor";
        getSchoolMajorDirection = CommentUrl + "User/School/schoolMajorDirection";
        bindUserSchool = CommentUrl + "User/School/bindUserSchool";
        getProvinceOrSchool = CommentUrl + "User/School/info";
        addUserQuestionIdentity = CommentUrl + "client/main/addUserQuestionIdentity";
        mockShareUrl = "https://m.yikaobang.com.cn/moniRanking/index.php?";
        statisticsShareUrl = "https://m.yikaobang.com.cn/moniExams/index.php?";
        analysisPraise = CommentUrl + "allquestion/errorCorrection/bkPraise";
        getMockPopData = CommentUrl + "exam/main/part";
        getMockModeStatisticsInfo = CommentUrl + "Exam/main/statForNewComputerTest";
        getAdjustInfo = CommentUrl + "exam/volunteer/adjustInfo";
        saveAdjustInfo = CommentUrl + "exam/volunteer/saveAdjustInfo";
        getAdjustQrCodeInfo = CommentUrl + "exam/volunteer/getAdjustQrCodeInfo";
        getAdjustRankList = CommentUrl + "exam/volunteer/adjustRankList";
        getSignLog = CommentNewUrl + "user/sign/getSignLog";
        getSignRanking = CommentNewUrl + "user/sign/getSignRanking";
        getRewardList = CommentNewUrl + "user/sign/getRewardList";
        signToSign = CommentNewUrl + "user/sign/sign";
        generateHelpCode = CommentNewUrl + "user/sign/generateHelpCode";
        useHelpCode = CommentNewUrl + "user/sign/useHelpCode";
        mineGetIconInfo = CommentNewUrl + "bootstrap/getIconInfo";
        touchShareUrl = CommentNewUrl + "user/sign/share";
        videoSummaryQuestionRedo = CommentNewUrl + "course/main/redo";
        videoQuestionInfo = CommentNewUrl + "course/video/questionInfo";
        downloadVideoBuryPoint = CommentNewUrl + "course/main/downloadVideo";
        shareHandout = CommentNewUrl + "course/main/shareHandout";
        doQuestionBuryPoint = CommentNewUrl + "course/main/questionDo";
        courseGiftList = CommentNewUrl + "course/main/giftItems";
        checkCouponUrl = CommentNewUrl + "shop/coupon/popup";
        getCoupon = CommentNewUrl + "shop/coupon/receive";
        signinAds = CommentNewUrl + "user/sign/ads";
        couponsList = CommentNewUrl + "shop/coupon/";
        personalDayCouponsList = CommentNewUrl + "user/main/coupon";
        newHomeTodayStatistics = CommentNewUrl + "user/main/todayTotal";
        newHomeInfo = CommentNewUrl + "user/main/getGzhArticle";
        newHomeKingKongArea = CommentNewUrl + "user/main/homePageJingangDistrict";
        chooseSchoolKingKongArea = CommentNewUrl + "chooseSchool/main/homePageModuleConfig";
        chooseSchoolTargetSchool = CommentNewUrl + "chooseSchool/main/targetSchool";
        chooseSchoolPermissionBtn = CommentNewUrl + "chooseSchool/main/permissionBtn";
        chooseSchoolGetPermissionList = CommentNewUrl + "chooseSchool/main/listAndUserPermission";
        chooseSchoolGetPermissionFree = CommentNewUrl + "chooseSchool/main/getActivityPermission";
        chooseSchoolGetPermissionGetFreePop = CommentNewUrl + "chooseSchool/main/freeViewPopup";
        chooseSchoolNoticeList = CommentNewUrl + "chooseSchool/updateNotice";
        chooseSchoolQuestionList = CommentNewUrl + "chooseSchool/question";
        chooseSchoolQuestionDetail = CommentNewUrl + "chooseSchool/getQuestionInfo";
        chooseSchoolMajorList = CommentNewUrl + "chooseSchool/main/majorList";
        chooseSchoolSaveScore = CommentNewUrl + "chooseSchool/main/saveScore";
        chooseSchoolChooseInfo = CommentNewUrl + "chooseSchool/main/chooseInfo";
        chooseSchoolCalendar = CommentNewUrl + "chooseSchool/main/schoolCalendar";
        chooseSchool1V1 = CommentNewUrl + "chooseSchool/public/tutoringContact";
        chooseSchoolTopSchoolInfo = CommentNewUrl + "chooseSchool/main/indexMixed";
        chooseSchoolSchoolList = CommentNewUrl + "chooseSchool/main/schoolList";
        chooseSchoolFilterData = CommentNewUrl + "chooseSchool/main/getSchoolSearchParams";
        chooseSchoolFeedBackCS = CommentNewUrl + "chooseSchool/main/getFeedBackCs";
        chooseSchoolTargetSchoolOpera = CommentNewUrl + "chooseSchool/main/targetSchool/save";
        questionKingKongArea = CommentNewUrl + "user/main/questionJingangDistrict";
        enableExpModule = CommentNewUrl + "bbs/main/getExpEnable";
        getShengYunGoodsNet = CommentUrl + "Shop/main/getShengYunGoods";
        getShengYunSet = CommentUrl + "Allquestion/sets/getShengYunSets";
        shengYunRegister = CommentUrl + "/user/main/shengYunRegister";
        questionCategory = CommentNewUrl + "question/category/list";
        questionChartFilter = CommentNewUrl + "question/category/option";
        questionChartTree = CommentNewUrl + "question/knowledgeTree";
        estimatedChange = CommentNewUrl + "studyReport/index";
        knowlwdgeMapOne = CommentNewUrl + "knowledge/map/getMasteryStat";
        knowlwdgeMapPoint = CommentNewUrl + "knowledge/map/getKnowledgeStat";
        studyReport = CommentNewUrl + "studyReport/header";
        weekOrMonthReport = CommentNewUrl + "studyReport/detail/header";
        knowledgeNodeList = CommentNewUrl + "knowledge/detail/list";
        knowlwdgePointTopData = CommentNewUrl + "knowledge/questionStat/getSummaryStat";
        knowlwdgePointDetail = CommentNewUrl + "knowledge/questionStat/getDetailStat";
        knowledgeQuestionList = CommentNewUrl + "knowledge/detail/questionList";
        aliyunCredentials = CommentNewUrl + "logger/question/credentials";
        questionTimeStatistics = CommentNewUrl + "knowledge/detail/stat";
        recommendVideoList = CommentNewUrl + "knowledge/detail/recommendVideo";
        nodeKnowledgeInfo = CommentNewUrl + "question/knowledgeNodeInfo";
        mockStatisticsStatInfo = CommentNewUrl + "exam/main/stat";
        mockStatisticsList = CommentNewUrl + "exam/main/knowledgeStat";
        mockStatisticsOutlines = CommentNewUrl + "exam/main/outlineStat";
        redoKnowledgeTree = CommentNewUrl + "question/redoKnowledgeTree";
        getMockStatisticsChatData = CommentNewUrl + "exam/main/chatStat";
        studyPlanNodeParams = CommentNewUrl + "studyPlan/main/params";
        userStudyPlanList = CommentNewUrl + "studyPlan/userStudyPlan/list";
        studyPlanParams = CommentNewUrl + "studyPlan/main/params";
        getKnowledgeQuestion = CommentNewUrl + "exam/main/knowledgeQuestion";
        getKnowledgeOutlinesQuestion = CommentNewUrl + "exam/main/examQuestion";
        studyPlanDrawUp = CommentNewUrl + "studyPlan/main/drawUp";
        receiveUserStudyPlan = CommentNewUrl + "studyPlan/userStudyPlan/receive";
        studyPlanQuestionCount = CommentNewUrl + "studyPlan/main/questionCount";
        studyPlanInProgress = CommentNewUrl + "studyPlan/main/inProgress";
        studyPlanRedoEveryTask = CommentNewUrl + "studyPlan/userStudyPlan/redoEveryTask";
        studyPlanQuestionList = CommentNewUrl + "studyPlan/main/questionList";
        redoStudyPlanQuestion = CommentUrl + "allquestion/main/redoAnswerWithStudyPlan";
        studyPlanPlanConfig = CommentNewUrl + "studyPlan/main/planConfig";
        schoolMenuList = CommentNewUrl + "chooseSchool/main/schoolModuleConfig";
        followSchool = CommentNewUrl + "chooseSchool/follow";
        cancelFollowSchool = CommentNewUrl + "chooseSchool/cancelFollow";
        getSchoolEnrollment = CommentNewUrl + "chooseSchool/getSchoolEnrollment";
        getDepartmentSchoolEnrollment = CommentNewUrl + "chooseSchool/getDepartmentSchoolEnrollment";
        getMajorEnrollment = CommentNewUrl + "chooseSchool/getMajorEnrollment";
        getDepartmentList = CommentNewUrl + "chooseSchool/main/getDepartmentInfo";
        getDepartmentMajorInfoList = CommentNewUrl + "chooseSchool/main/getDepartmentMajorInfo";
        schoolDetails = CommentNewUrl + "chooseSchool/getSchoolDetail";
        getScoreLine = CommentNewUrl + "chooseSchool/getCutoffScore";
        getScoreLineParams = CommentNewUrl + "/chooseSchool/getCutoffScoreSearchParams";
        searchSchoolOrMajor = CommentNewUrl + "chooseSchool/main/search";
        followSchoolList = CommentNewUrl + "chooseSchool/getFollowSchool";
        followMajor = CommentNewUrl + "chooseSchool/getFollowMajor";
        getRecruitInfo = CommentNewUrl + "chooseSchool/getRecruitInfo";
        getRecruitInfoSearchParams = CommentNewUrl + "chooseSchool/getRecruitInfoSearchParams";
        hotSchoolList = CommentNewUrl + "chooseSchool/public/hotSchool";
        hotMajorList = CommentNewUrl + "chooseSchool/public/hotMajor";
        getSchoolListForMajor = CommentNewUrl + "chooseSchool/main/getSchoolListForMajor";
        getAdmissionBrochure = CommentNewUrl + "chooseSchool/getProspectus";
        indexForMajorList = CommentNewUrl + "chooseSchool/main/indexForMajorList";
        indexForSchoolList = CommentNewUrl + "chooseSchool/main/indexForSchoolList";
        prospectusViewCount = CommentNewUrl + "chooseSchool/prospectusViewCount";
        getMajorRecruitInfo = CommentNewUrl + "chooseSchool/getMajorRecruitInfo";
        getMajorScoreInfo = CommentNewUrl + "chooseSchool/getMajorScoreInfo";
        targetSchoolSearchList = CommentNewUrl + "chooseSchool/main/targetSchool/searchList";
        saveDelTargetSchool = CommentNewUrl + "chooseSchool/main/targetSchool/save";
        getOpenMajorList = CommentNewUrl + "chooseSchool/main/getOpenMajorList";
        incrViewCount = CommentNewUrl + "chooseSchool/main/incrViewCount";
        rankShareUrl = commentH5Url + "rank.html?";
    }
}
