package com.plv.rtc.urtc.enummeration;

/* loaded from: classes5.dex */
public enum URTCSdkNetWorkQuality {
    U_CLOUD_RTC_SDK_NET_WORK_QUALITY_UNKNOWN,
    U_CLOUD_RTC_SDK_NET_WORK_QUALITY_EXCELLENT,
    U_CLOUD_RTC_SDK_NET_WORK_QUALITY_GOOD,
    U_CLOUD_RTC_SDK_NET_WORK_QUALITY_NORMAL,
    U_CLOUD_RTC_SDK_NET_WORK_QUALITY_BAD,
    U_CLOUD_RTC_SDK_NET_WORK_QUALITY_TERRIBLE,
    U_CLOUD_RTC_SDK_NET_WORK_QUALITY_DOWN
}
